services:
  db:
    image: postgres:15-alpine
    container_name: smart_logger_db
    environment:
      POSTGRES_DB: smart_logger_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge