app:
  redis:
    account-ttl: 10m

jwt:
  secret:
    key: ls2cNJbDUq2wly1Q+84QqvXcdP3iasWTj0XP0sYmKP0=

server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: redis
      port: 6379
      connect-timeout: 500ms
      timeout: 500ms

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: protected_route
              uri: lb://ingestion-service
              predicates:
              - Path=/api/ingestion/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-service:8761/eureka/}
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}