app:
  redis:
    account-ttl: 10m

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway.mvc: DEBUG

jwt:
  secret:
    key: ls2cNJbDUq2wly1Q+84QqvXcdP3iasWTj0XP0sYmKP0=

server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: redis
      port: 6379
      connect-timeout: 500ms
      timeout: 500ms

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth_api_route
              uri: lb://auth-service
              predicates:
                - Path=/api/**
            - id: ingestion_api_route
              uri: lb://ingestion-service
              predicates:
                - Path=/api/**
            - id: core_api_route
              uri: lb://core-service
              predicates:
                - Path=/api/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-service:8761/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    hostname: api-gateway
    instance-id: ${spring.application.name}:${random.value}
